version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: musicservicedb
    environment:
      MYSQL_DATABASE: musicservicedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  musicservice:
    image: licensing-service:0.0.1-SNAPSHOT
    depends_on:
      - musicservicedb
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:3306/musicservicedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  musicservicedb-data: