server:
  port: 8081
spring:
  application:
    name: MusicService
  datasource:
    url: jdbc:postgresql://musicservicedb:3306/db
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  sql:
    init:
      mode: always
