version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: musicservicedb
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
    ports:
      - 5432:5432
  musicservice:
    image: music-service:0.0.1-SNAPSHOT
    container_name: music-service
    depends_on:
      - postgres
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://musicservicedb:5432/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  musicservice-data: