version: '3.8'
services:
  postgres-db-dev:
    image: postgres:latest
    container_name: musicservicedb-dev
    environment:
      POSTGRES_DB: db-dev
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
    ports:
      - 5432:5432
  postgres-db-prod:
    image: postgres:latest
    container_name: musicservicedb-prod
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password
    ports:
      - 5433:5432
  musicservice:
    image: music-service:0.0.1-SNAPSHOT
    container_name: music-service
    depends_on:
      - postgres-db-dev
      - postgres-db-prod
    ports:
      - 8081:8081
    environment:
      SPRING_ACTIVE_PROFILE: "dev"
      SPRING_DATASOURCE_URL: jdbc:postgresql://musicservicedb-dev:5432/db-dev
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  musicservice-data: