spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db-prod
    driver-class-name: org.postgresql.Driver
    username: produser
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy