server:
  port: 8081
spring:
  application:
    name: music-service
  profiles:
    active: dev
  sql:
    init:
      mode: always

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8073/eureka/